name    'sbadia-skel'
version '0.0.1'
source  'https://github.com/sbadia/puppet-skel'
author  'Sebastien Badia'
license 'GPLv3'
summary 'Puppet skel Module'
description 'Module to install skel using puppet'
project_page 'https://github.com/sbadia/puppet-skel/'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
